MindscapeHQ/raygun4net

- README.md
Existing link is a 404. I'm guessing they renamed it.
> Update link and extension name in README.md

- Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiMessageBuilder.cs
- Mindscape.Raygun4Net.Xamarin.Android/RaygunClient.cs
- Mindscape.Raygun4Net.Xamarin.Mac/RaygunClient.cs
- Mindscape.Raygun4Net.Xamarin.iOS/RaygunClient.cs
- Mindscape.Raygun4Net/RaygunClient.cs
- Mindscape.Raygun4Net/RaygunClientBase.cs
- Mindscape.Raygun4Net/RaygunMessageBuilder.cs
- Mindscape.Raygun4Net/RaygunSettings.cs
- Mindscape.Raygun4Net2/RaygunClient.cs
- Mindscape.Raygun4Net2/RaygunMessageBuilder.cs
- Mindscape.Raygun4Net2/RaygunSettings.cs
- Mindscape.Raygun4Net4/Mindscape.Raygun4Net4.csproj
Since that Raygun client sends json data to his service, the request should include the Content-Type header set to "application/json; charset=uff-8".
The only clients that i havent done this change are the WindowsPhone and the WinRT clients. They had already the content-type setted but with the value "application/x-raygun-message".
> Improve request header

- Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiMessageBuilder.cs
- Mindscape.Raygun4Net/RaygunClientBase.cs
- Mindscape.Raygun4Net/RaygunMessageBuilder.cs
- Mindscape.Raygun4Net/RaygunSettings.cs
- Mindscape.Raygun4Net2/RaygunMessageBuilder.cs
- Mindscape.Raygun4Net2/RaygunSettings.cs
- Mindscape.Raygun4Net4/Mindscape.Raygun4Net4.csproj
Now, it is possible to set the ApplicationVersion in the config file or at the initialization of the application
```
protected void Application_Start()
{
var applicationVersion = Assembly.GetExecutingAssembly().GetName().Version.ToString();
Mindscape.Raygun4Net.RaygunSettings.Settings.ApplicationVersion = applicationVersion;
...
}
```
i havent done any work in the following projects since that i don't have the libraries to test them:
- WindowsPhone
- WindowsStore
- WinRT
- Xamarin.*
I had to make a little hack to the WebApi project since that the initialization of the ApplicationVersion is not the same as the other projects.
> Improve appversion configuration

- Mindscape.Raygun4Net.Xamarin.iOS/RaygunClient.cs
Fix based on existing check for `DeviceId` in `BuildRaygunIdentifierMessage()`.
https://github.com/MindscapeHQ/raygun4net/blob/v4.2.0/Mindscape.Raygun4Net.Xamarin.iOS/RaygunClient.cs#L474
> Fixes #232 - ArgumentNullException thrown by Identify(string userId)

- Mindscape.Raygun4Net.WebApi/IRaygunWebApiClientProvider.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiControllerActivator.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiExceptionLogger.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiFilters.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiSelectors.cs
Add HttpRequestMessage to the generateRaygunClient function used to instatiate a custom RaygunWebApiClient. This lets people use the current Http Request info when constructing a client.
Deprecate the old Attach method which takes Func&lt;RaygunWebApiClient&gt; in favour of the one that takes Func&lt;HttpRequestMessage, RaygunWebApiClient&gt;
Probably needs a full version rev as it adds an Obsolete attribute to Attach, although existing clients shouldn't need to actually change anything unless they have warnings as errors turned on.
> Add HttpRequestMessage to the generateRaygunClient function

- Mindscape.Raygun4Net.Xamarin.iOS.Unified/Mindscape.Raygun4Net.Xamarin.iOS.Unified.csproj
- Mindscape.Raygun4Net.Xamarin.iOS/Mindscape.Raygun4Net.Xamarin.iOS.csproj
This directs SimpleJson to use reflection instead of dynamically compiled LINQ expressions for deserialization. Dynamically compiled LINQ requires Mono.Dynamic.Interpreter on iOS, adding about 1MB per architecture to an iOS app.
> Build for Xamarin.iOS with SIMPLE_JSON_NO_LINQ_EXPRESSION.

- Mindscape.Raygun4Net.AspNetCore/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.AspNetCore/RaygunAspNetMiddleware.cs
- Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs
- Mindscape.Raygun4Net.AspNetCore/RaygunClientProvider.cs
- Mindscape.Raygun4Net.AspNetCore/project.json
- Mindscape.Raygun4Net.AspNetCore/readme.txt
When sending exceptions manually you need to be able to set the HttpContext to ensure context information is sent with the Crash Report if available.
When implementing a custom IRaygunAspNetCoreClientProvider you also need access to the HttpContext to determine the logged in user for setting the client RaygunIdentifierMessage.
This change allows both these requirements by exposing overloaded methods that allows the user to pass the current HttpContext.
> Set HttpContext on client

- AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.Xamarin.iOS.Tests/Properties/AssemblyInfo.cs
- Mindscape.Raygun4Net.Xamarin.iOS.Tests/RaygunClientTests.cs
- Mindscape.Raygun4Net.Xamarin.iOS.Unified/Properties/AssemblyInfo.cs
- Mindscape.Raygun4Net.Xamarin.iOS/Builders/RaygunErrorMessageBuilder.cs
- Mindscape.Raygun4Net.Xamarin.iOS/Properties/AssemblyInfo.cs
Made the stack trace parsing more flexible to take into account stack traces without debug symbols and line numbers. This also fixes the hashing of xamarin ios errors that rely on the class name and method name being valid. These properties were not filled out if the line number was not present.
> Xamarin iOS stack trace fix

- Mindscape.Raygun4Net.AspNetCore/Builders/RaygunAspNetCoreRequestMessageBuilder.cs
- Mindscape.Raygun4Net.AspNetCore/RaygunAspNetMiddleware.cs
- Mindscape.Raygun4Net.AspNetCore/RaygunSettings.cs
- Mindscape.Raygun4Net.AspNetCore/project.json
- Mindscape.Raygun4Net.AspNetCore/project.lock.json
I don't think this is necessarily ready for merge but I wanted to get it shared.....
If my understanding is correct in how ASP.NET Core handles requests, then the raw data handling currently in raygun is broken WRT ASP.NET Core in the following ways:
1. Non-Form streams are not rewindable, so this line:
request.Body.Seek(0, SeekOrigin.Begin);
breaks as Seek is not supported, and the stream has already been read. To fix, I implemented an update to the middleware that replaces the incoming stream with one that has CanSeek == true. This is controlled by a new property "TransformRequestStream"
2. After we have a rewindable stream, the code that strips out ignored properties uses request.Form, which is not populated for non urlencoded form posts. It looks like the code to do this is dead code …
> Allowing Raw Data capture for ASP.NET Core

- Mindscape.Raygun4Net.Xamarin.Android.Tests/RaygunClientTests.cs
- Mindscape.Raygun4Net.Xamarin.Android/RaygunClient.cs
In recent versions of Xamarin (not sure on exact release, but I assume Xamarin.Android 6.1 as the JNI architecture was changed then) the first line in the stack trace had changed to include the top level throwable class name rather than "exception".
Added handling for proxy stack traces in Xamarin.Android 6.1(?)+ and associated tests.
Also fixed handling for non-wrapped throwables which will have `JavaProxyThrowable` on line 2 of the stack trace, and no `Caused by: ` prefix.
```
--- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120):0
Caused by: java.lang.reflect.InvocationTargetException
java.lang.reflect.Method.invoke(Native Method):0 …
```
> Fix ignore JavaProxyThrowable handling in recent Xamarin releases

- Mindscape.Raygun4Net.AspNetCore/Mindscape.Raygun4Net.AspNetCore.csproj
- Mindscape.Raygun4Net.AspNetCore/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.AspNetCore/readme.txt
- Mindscape.Raygun4Net.AspNetCore2.Tests.TestLib/Mindscape.Raygun4Net.AspNetCore2.Tests.TestLib.csproj
- Mindscape.Raygun4Net.AspNetCore2.Tests/Mindscape.Raygun4Net.AspNetCore2.Tests.csproj
- Mindscape.Raygun4Net.NetCore.Common/Messages/RaygunClientMessage.cs
- Mindscape.Raygun4Net.NetCore.Common/Mindscape.Raygun4Net.NetCore.Common.csproj
- Mindscape.Raygun4Net.NetCore.Common/SimpleJson.cs
- Mindscape.Raygun4Net.NetCore.Tests/Mindscape.Raygun4Net.NetCore.Tests.csproj
- Mindscape.Raygun4Net.NetCore.Tests/SimpleJsonTests.cs
- Mindscape.Raygun4Net.NetCore/Mindscape.Raygun4Net.NetCore.csproj
- Mindscape.Raygun4Net.NetCore/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.NetCore/readme.txt
- buildAspNetCore.ps1
- buildNetCore.ps1
It appears modifications had been made to the SimpleJson class to work with Net core, however these modifications weren't needed and broke the recursive serialization checks. The PR brings the implementation back in line with the version in the full framework project and resolves #392 
Other minor fixes
- Removed Newtonsoft.Json as a package reference.
- Fixed file references between projects to be project references and not nuget references.
- Fixed SimpleJson unit tests as these must have never been run.
> Fix StackOverflowException with .NET Core client

- AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.Core.Signed.nuspec
- Mindscape.Raygun4Net.Core.nuspec
- Mindscape.Raygun4Net.Mvc.Signed.nuspec
- Mindscape.Raygun4Net.Mvc.nuspec
- Mindscape.Raygun4Net.Signed.nuspec
- Mindscape.Raygun4Net.WebApi.Signed.nuspec
- Mindscape.Raygun4Net.WebApi.nuspec
- Mindscape.Raygun4Net.WebApi/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiControllerActivator.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiFilters.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiSelectors.cs
- Mindscape.Raygun4Net.nuspec
- Mindscape.Raygun4Net/RaygunClient.cs
- Mindscape.Raygun4Net/RaygunHttpModule.cs
- Mindscape.Raygun4Net4/RaygunClient.cs
Any part of Raygun4Net that automatically sends exceptions will now add the "UnhandledException" tag just like other providers. This is used to distinguish uncaught exceptions (likely application crashes) vs exceptions sent from try/catch blocks. Currently applies to ASP .NET, MVC and WebAPI projects.
> Automatic unhandled exception tag

- Mindscape.Raygun4Net.WebApi/Mindscape.Raygun4Net.WebApi.csproj
- Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiDelegatingHandler.cs
- Mindscape.Raygun4Net.WebApi/WebClientHelper.cs
- Mindscape.Raygun4Net/SimpleJson.cs
- Mindscape.Raygun4Net4/Mindscape.Raygun4Net4.csproj
- Mindscape.Raygun4Net4/RaygunClient.cs
HttpWeblcient is instantiated too many times and causes network flooding with DNS resolutions.
Fix: Implemented singleton Client.
Writing to the System.Diagnostics.Trace some times fails and crashes the app.
Wrapped try trace writer in a try-catch block
> Intercomm ticket resolution

- README.md
Overview
---
This PR is to implement information within the README.md about sending further information about HTTP request details if you are manually sending exceptions. This is so when future customers won't have to contact us via Intercom as well
> Implement HTTP request instructions for manually sent excpetions

- AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.Core.Signed.nuspec
- Mindscape.Raygun4Net.Core.nuspec
- Mindscape.Raygun4Net.Mvc.Signed.nuspec
- Mindscape.Raygun4Net.Mvc.nuspec
- Mindscape.Raygun4Net.Signed.nuspec
- Mindscape.Raygun4Net.WebApi.Signed.nuspec
- Mindscape.Raygun4Net.WebApi.nuspec
- Mindscape.Raygun4Net.nuspec
Cache the environment information for the DotNet4.0 provider
The actual changes: https://github.com/MindscapeHQ/raygun4net/commit/802148d4fccb2eee513f6f5392687be6d41a022e
> Cache the environment information for the DotNet4.0 provider

- Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs
- Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
Resolves #428.
Adds a `SendInBackground` overload to the NetCore packages which supports sending an `Exception` with a `RaygunIdentifierMessage`.
This mirrors what is currently available in the `Mindscape.Raygun4Net` package:
https://github.com/MindscapeHQ/raygun4net/blob/d59749c03519a5210409408a7aa2bb1a122c5e25/Mindscape.Raygun4Net/RaygunClient.cs#L289-L296
> Add SendInBackground overload to NetCore projects to support sending an Exception with a RaygunIdentifierMessage

- Mindscape.Raygun4Net.AspNetCore/README.md
Wrap code blocks in appropriate markdown for better formatting
> Update formatting in .NET Core readme

- Mindscape.Raygun4Net.Xamarin.iOS.Unified/RaygunFileManager.cs
- Mindscape.Raygun4Net.Xamarin.iOS/RaygunSettings.cs
Per the [discussion](https://raygun.com/forums/thread/163861) on the RayGun Forums, I have added support for configuring the path of the directory used to store crash report data into RaygunSettings.
This is necessary because if you are writing a document based Xamarin.iOS app, the "RaygunIO" folder will be visible with the local documents directory of your app (and any other document browser based app such as Files).
> Make the Raygun directory configurable for Xamarin.iOS

- Mindscape.Raygun4Net.AspNetCore/README.md
- Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs
When using the `RaygunClient.Send()` overload in an ASP.NET Core MVC application, the HTTP request details are not being included in the message being sent to the API. This change adds an override for the `SendAsync` method which awaits the retrieval of the request details and sets them on the ThreadLocal value which is used in the `BuildMessage` method.
- Add override for the SendAsync method in the ASP.NET Core RaygunClient 
- The HTTP context is not set to null until after the request and response messages have been built
- Add docs to the readme for the case where a singleton RaygunClient object is used
> Add an override for the SendAsync method in the ASP.NET CORE RaygunClient

- Mindscape.Raygun4Net.AspNetCore/Mindscape.Raygun4Net.AspNetCore.csproj
- Mindscape.Raygun4Net.AspNetCore/Properties/AssemblyVersionInfo.cs
This PR increments the version numbers to prep for the release of this PR that allows Raygun4Net.AspNetCore to be used with .Net 5, #454 
Changes include:
- Bumping version numbers for the AspNetCore project.
> Bump version numbers for release

- Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
Add ConfigureAwait(false) to library calls to allow correct operation in certain .Net Framework scenarios. (e.g. WinForms & WebForms).
> Add ConfigureAwait(false)

- Mindscape.Raygun4Net.AspNetCore/Mindscape.Raygun4Net.AspNetCore.csproj
- Mindscape.Raygun4Net.AspNetCore/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.AspNetCore/README.md
- Mindscape.Raygun4Net.NetCore.Common/Messages/RaygunClientMessage.cs
- Mindscape.Raygun4Net.NetCore.Common/Mindscape.Raygun4Net.NetCore.Common.csproj
- Mindscape.Raygun4Net.NetCore/Mindscape.Raygun4Net.NetCore.csproj
- Mindscape.Raygun4Net.NetCore/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.NetCore/README.md
This PR increments the version numbers to prep for the release of this PR #455 that adds in ConfigureAwait(false) to the awaited calls in the Mindscape.Raygun4net.NetCore.Common library
> Bump version numbers for release of PR #455

- Mindscape.Raygun4Net.AspNetCore/Builders/RaygunAspNetCoreRequestMessageBuilder.cs
The check for `request.HasFormContentType` when trying to get cookies from the request should not be there as the Form content has no bearing on a request containing cookies or not. It looks like this was copied over from the original implementation.
I've also added a message to the cookies list if this method fails in line with the other methods in this class.
> Fix missing cookie collection in ASP.NET Core provider

- Mindscape.Raygun4Net.AspNetCore/RaygunAspNetMiddleware.cs
- Mindscape.Raygun4Net.AspNetCore2.Tests/ExampleRaygunAspNetCoreClientProvider.cs
When the UnhandledException tag is added by the ASP.NET Core middleware, tags are initialized as a string array, which
is of fixed size, preventing additional tags from being added (for example when overriding the Raygun client provider). Initializing as a `List<string>` instead will fix this.
fixes #466
> Initialize Tags as List<string> instead of string array in ASP.NET Core middleware

- Mindscape.Raygun4Net.NetCore/README.md
- README.md
This PR is to update the readme for the .NET Core provider so it is up to date
Changes made:
Raygun4Net.NetCore: 
- Updated instructions on how to find API key
- Update installation instructions to match public docs
- Added link to our public docs
- Code formatting
Raygun4Net:
- Add note that package supports up to .NET 7
- Updated instructions on how to find API key
- Added link to our public docs
- Removed ! Important change ! section
- Removed mention of VS NuGet extension
- Removed mention of VS 2008
- Linked to .NET Core package
- Removed mentions of Windows Store and Windows Phone
> Update .NET providers readme

- README.md
This PR is to update the README to distinguish installation instructions for ASP.NET 5+ (Also known and ASP.NET Core) and ASP.NET Framework
> [MC-88] README changes for ASP.NET

- Mindscape.Raygun4Net.AspNetCore/Mindscape.Raygun4Net.AspNetCore.csproj
- Mindscape.Raygun4Net.Azure.WebJob.nuspec
- Mindscape.Raygun4Net.Azure.WebJob/Mindscape.Raygun4Net.Azure.WebJob.csproj
- Mindscape.Raygun4Net.ClientProfile/Mindscape.Raygun4Net.ClientProfile.csproj
- Mindscape.Raygun4Net.Common/Mindscape.Raygun4Net.Common.csproj
- Mindscape.Raygun4Net.Core.Signed.nuspec
- Mindscape.Raygun4Net.Core.nuspec
- Mindscape.Raygun4Net.Core/Mindscape.Raygun4Net.Core.csproj
- Mindscape.Raygun4Net.Mvc.Signed.nuspec
- Mindscape.Raygun4Net.Mvc.nuspec
- Mindscape.Raygun4Net.Mvc/Mindscape.Raygun4Net.Mvc.csproj
- Mindscape.Raygun4Net.NetCore.Common/Mindscape.Raygun4Net.NetCore.Common.csproj
- Mindscape.Raygun4Net.NetCore/Mindscape.Raygun4Net.NetCore.csproj
- Mindscape.Raygun4Net.Signed.nuspec
- Mindscape.Raygun4Net.Tests/Mindscape.Raygun4Net.Tests.csproj
- Mindscape.Raygun4Net.WebApi.Signed.nuspec
- Mindscape.Raygun4Net.WebApi.Tests/Mindscape.Raygun4Net.WebApi.Tests.csproj
- Mindscape.Raygun4Net.WebApi.nuspec
- Mindscape.Raygun4Net.WebApi.sln
- Mindscape.Raygun4Net.WebApi/Mindscape.Raygun4Net.WebApi.csproj
- Mindscape.Raygun4Net.nuspec
- Mindscape.Raygun4Net/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net4.ClientProfile/Mindscape.Raygun4Net4.ClientProfile.csproj
- Mindscape.Raygun4Net4.Nuget.Tests/Mindscape.Raygun4Net4.Nuget.Tests.csproj
- Mindscape.Raygun4Net4/Mindscape.Raygun4Net4.csproj
- Mindscape.Raygun4Net4/Properties/AssemblyVersionInfo.cs
- build.ps1
Updating down stream packages 
Also updated:
1. package number
2.  icon,
3.  licence (refence)
4. signed the regular packages signed (so we can deprecate the `<xyz>.Signed` packages later
> Updating down stream packages (that use raygun4net )

- .gitignore
- AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.Azure.WebJob.nuspec
- Mindscape.Raygun4Net.Azure.WebJob/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.ClientProfile/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.Core.Signed.nuspec
- Mindscape.Raygun4Net.Core.nuspec
- Mindscape.Raygun4Net.Core/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.Mvc.Signed.nuspec
- Mindscape.Raygun4Net.Mvc.nuspec
- Mindscape.Raygun4Net.Mvc/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.Signed.nuspec
- Mindscape.Raygun4Net.WebApi.Signed.nuspec
- Mindscape.Raygun4Net.WebApi.nuspec
- Mindscape.Raygun4Net.WebApi/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net.nuspec
- Mindscape.Raygun4Net/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net4.ClientProfile/Properties/AssemblyVersionInfo.cs
- Mindscape.Raygun4Net4.Nuget.Tests/Mindscape.Raygun4Net4.Nuget.Tests.csproj
- Mindscape.Raygun4Net4/Properties/AssemblyVersionInfo.cs
Bump version numbers
When a sln references several raygun4net packages  the raygun4net.dll can have version conflicts.
To resolve this we could do a bit of a rebuild of the nuget packages (maybe later) or just bump the version numbers so they all will use the same dlls
> bump all the versions

- global.json
Version was causing Rider to use .NET 8 as it didn't understand the `Version`
https://learn.microsoft.com/en-us/dotnet/core/tools/global-json
Changed to specify v6 and allow any Minor version, but disallow pre-releases.
> Fixed global.json file to minor versions and no pre-releases

- CHANGE-LOG.md
- Mindscape.Raygun4Net.WebApi/Mindscape.Raygun4Net.WebApi.csproj
Removed the reference to `Mindscape.Raygun4Net.Common` and Linked the 3 dependent files into the WebApi project.
I double checked the old nuget packages and they have no reference to Common. 
This resolves a bug raised on the forum: https://raygun.com/forums/thread/184633
Release v7.1.1 for WebApi was built off the branch and release to nuget.
> Remove Common ref on WebApi

- GlobalAssemblyInfo.cs
- Mindscape.Raygun4Net.NetCore/Mindscape.Raygun4Net.NetCore.csproj
- pack-all.ps1
To fix dependent projects referencing the wrong version this adds the missing `AssemblyVersion` used by StrongName.
> Add the missing AssemblyVersion to AssemblyInfo

- CHANGE-LOG.md
- Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
- Mindscape.Raygun4Net.NetCore.Common/UnhandledExceptionBridge.cs
- Mindscape.Raygun4Net.NetCore.Tests/Model/FakeRaygunClient.cs
- Mindscape.Raygun4Net.NetCore.Tests/RaygunClientBaseTests.cs
This is to fix #508 
Use WeakReference to wrap the event subcribers.
This allows for multiple RaygunClient instances, and they are no longer kept alive by the event subscription.
> Convert the GlobalExceptionBridge to use WeakReference for events

- Mindscape.Raygun4Net.NetCore.Common/UnhandledExceptionBridge.cs
Effectively manage the lifecycle of handlers
This change should be released under 8.2.1
Further fixes #508 and extends on #509
> Convert the multicast delegate into a list of handlers

- Mindscape.Raygun4Net.NetCore.Common/UnhandledExceptionBridge.cs
- Mindscape.Raygun4Net.NetCore.Tests/UnhandledExceptionBridgeTests.cs
This addresses the Lock Recursion exception raised in #513 
Don't try to clean up the handlers in the invocation.
Instead move all the logic to the add method.
This is slightly less optimal on the memory, but makes managing the locks across threads much simpler and less error prone.
The test was created and was able to reproduce the issue in 9.0.0, the "broken" test now passes.
> Fix Lock recursion 

- CHANGE-LOG.md
- Mindscape.Raygun4Net.WebApi/Builders/RaygunWebApiRequestMessageBuilder.cs
- Mindscape.Raygun4Net.WebApi/Filters/RaygunWebApiActionFilter.cs
- Mindscape.Raygun4Net.WebApi/Filters/RaygunWebApiExceptionFilter.cs
- Mindscape.Raygun4Net.WebApi/IRaygunWebApiClientProvider.cs
- Mindscape.Raygun4Net.WebApi/Mindscape.Raygun4Net.WebApi.csproj
- Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiClientProvider.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiMessageBuilder.cs
- Mindscape.Raygun4Net.WebApi/Selectors/RaygunWebApiActionSelector.cs
- Mindscape.Raygun4Net.WebApi/Selectors/RaygunWebApiControllerSelector.cs
- Mindscape.Raygun4Net.WebApi/Services/RaygunWebApiControllerActivator.cs
- Mindscape.Raygun4Net.WebApi/Services/RaygunWebApiExceptionLogger.cs
Sometimes a null-ref exception occurs when building the message due to the fields being persistent in the RaygunClient when using SendInBackground. 
This PR makes the data scoped to the function and passed through.
Also cleaned up some methods now that the version of C# has been updated, we can use optional parameters.
> Remove the usage of LocalThread in .NET Framework versions

- Mindscape.Raygun4Net.Core/IRaygunMessageBuilder.cs
- Mindscape.Raygun4Net.Core/Messages/RaygunMessage.cs
- Mindscape.Raygun4Net.NetCore.Common/Messages/RaygunMessage.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs
- Mindscape.Raygun4Net4/RaygunMessageBuilder.cs
- Raygun.CrashReporting.sln.DotSettings
When the `RaygunWebApiClient` is created using the empty ctor, it does not new up the background processor and this causes an exception to be thrown when `SendInBackground` is called.
```
System.NullReferenceException : Object reference not set to an instance of an object.
at Mindscape.Raygun4Net.WebApi.RaygunWebApiClient.StripAndSendInBackground(Exception exception, IList`1 tags, IDictionary userCustomData, Nullable`1 currentTime, Action`1 customiseAction) in C:\Codez\raygun4net\Mindscape.Raygun4Net.WebApi\RaygunWebApiClient.cs:line 588
at Mindscape.Raygun4Net.WebApi.RaygunWebApiClient.SendInBackground(Exception exception, IList`1 tags, IDictionary userCustomData) in C:\Codez\raygun4net\Mindscape.Raygun4Net.WebApi\RaygunWebApiClient.cs:line 474
```
> Fix NRE when calling SendInBackground

- CHANGE-LOG.md
Added some clarity in the change log around `SetCurrentHttpRequest` being removed.
> Updated change log for v9.0.2

- CHANGE-LOG.md
- Mindscape.Raygun4Net.Core/IRaygunMessageBuilder.cs
- Mindscape.Raygun4Net.WebApi/Builders/RaygunRequestMessageBuilder.cs
- Mindscape.Raygun4Net.WebApi/Builders/RaygunWebApiRequestMessageBuilder.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiMessageBuilder.cs
- Mindscape.Raygun4Net4/RaygunClient.cs
- Mindscape.Raygun4Net4/RaygunMessageBuilder.cs
- RaygunClient was missing data entirely
- RaygunWebApiClient only worked for new versions of Web API
- Builder for WebApi didn't collect form data (it got querystring data instead of form?)
> Fix for HTTP Data in .NET Framework libs

- CHANGE-LOG.md
- Mindscape.Raygun4Net.AspNetCore.Tests/Program.cs
- Mindscape.Raygun4Net.NetCore.Common/Builders/EnvironmentProviders/EnvironmentVariablesProvider.cs
- Mindscape.Raygun4Net.NetCore.Common/Builders/RaygunEnvironmentMessageBuilder.cs
- Mindscape.Raygun4Net.NetCore.Common/Messages/RaygunEnvironmentMessage.cs
- Mindscape.Raygun4Net.NetCore.Common/RaygunSettings.cs
- Mindscape.Raygun4Net.NetCore.Tests/RaygunBreadcrumbsTests.cs
- Mindscape.Raygun4Net.NetCore.Tests/RaygunMessageBuilderTests.cs
New settings to enable capturing environment variables. 
```csharp
builder.Services.AddRaygun(builder.Configuration, settings =>
{
settings.EnvironmentVariables.Add("USER*");
settings.EnvironmentVariables.Add("POSH_*");
});
```
Can do:
- Exact Match: `PATH`
- Starts With: `POSH_*`
- Ends With: `*_VALUE`
- Contains: `*_banana_*`
If you enter `*` only it will return nothing as we don't want to capture everything, variables should be opt-in and explicit, not capture everything and potentially leak sensitive data by mistake.
> Added support for capturing Environment Variables

- Mindscape.Raygun4Net.Core/Breadcrumbs/RaygunBreadcrumb.cs
- Mindscape.Raygun4Net.NetCore.Common/Breadcrumbs/RaygunBreadcrumb.cs
- Mindscape.Raygun4Net.NetCore.Common/Breadcrumbs/RaygunBreadcrumbs.cs
- Mindscape.Raygun4Net4/Breadcrumbs/HttpBreadcrumbStorage.cs
- Mindscape.Raygun4Net4/Breadcrumbs/RaygunBreadcrumbs.cs
- Mindscape.Raygun4Net4/RaygunClient.cs
Also skip StackTrace probing, when BreadCrumb is prefilled.
> Reduce overhead from using RaygunBreadcrumb by lazy allocation of CustomData

- CHANGE-LOG.md
- Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
- Mindscape.Raygun4Net.NetCore.Tests/UnhandledExceptionBridgeTests.cs
Fixes an issue where the reference to the delegate that sends unhandled exceptions to the client is garbage collected despite the client being alive. This can cause uncaught exceptions not to be reported to Raygun.
This is fixed by adding a strong reference in the client so that while the client is alive the delegate should be alive too.
> Fix Issue Where WeakReference Delegate is Garbage Collected While Client is Alive

- Mindscape.Raygun4Net.Core/Builders/RaygunErrorMessageBuilder.cs
- Mindscape.Raygun4Net.NetCore.Common/Builders/RaygunErrorMessageBuilder.cs
- Mindscape.Raygun4Net.NetCore.Common/Platforms/AndroidPlatform.cs
Fix the module name, to fully qualify the path to load.
That way if the executing directory is different to the module directory, it can load the file correctly.
Also remove the unhandled = true flag from Android
> Add fully quality module name and remove the android handled

- CHANGE-LOG.md
- Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
`GetAwaiter().GetResult()` is really not ideal, we have to continue to support the synchronous api, so it's required.
Internally we should be avoiding the usage of Send()
> Add `ConfigureAwait(false)` to the blocking and non blocking Send calls

- CHANGE-LOG.md
- Mindscape.Raygun4Net.Core/Builders/RaygunErrorMessageBuilder.cs
- Mindscape.Raygun4Net.NetCore.Common/Builders/RaygunErrorMessageBuilder.cs
There is a possibility that a frame does not have any debugging information attached to it.
This happens when DebugSymbols is set to "None", and the output is in Release mode. The result is DebugInfo but it does not have a signature or other properties.
This addresses that particular scenario, by null checking the debug info as well as the signature before attempting to create the lookup dictionary.
```
System.Exception: Really bad explosion
at MyCoolClassLibrary.AwesomeClass.ThrowsAnException()
at Program.<Main>$(String[] args)
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue …
```
> Fix nulls in debug info dictionary

- CHANGE-LOG.md
- Mindscape.Raygun4Net4/RaygunClient.cs
- Mindscape.Raygun4Net4/RaygunHttpModule.cs
Update the `RaygunHttpModule` for ASP.NET Framework applications to store and use a single `RaygunClient` instance. This avoids a new `RaygunClient` and in turn a `ThrottledBackgroundMessageProcessor`, from being created for every exception handled by the `RaygunHttpModule`. The `ThrottledBackgroundMessageProcessor` creates a number of background worker threads, so instantiating it for each exception can be costly.
> Use Singleton RaygunClient in RaygunHttpModule (.NET Framework)

- CHANGE-LOG.md
- Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
This change is required for updates to Serilog provider where Serilog uses the base implementation of `SendInBackground` but depends on `IRaygunUserProvider` to get the user info from `HttpContextAccessor.HttpContext`
When the build message is sent as a delegate to `Enqueue` it gets executed out of context and the information is lost. 
There is a minor overhead in memory building the message up front but this only occurs when there's a huge number of exceptions being thrown.
> Build message before queuing it

- CHANGE-LOG.md
- Mindscape.Raygun4Net.NetCore.Common/Offline/OfflineStoreBase.cs
- Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs
- Mindscape.Raygun4Net.NetCore.Common/RaygunSettingsBase.cs
- Mindscape.Raygun4Net.NetCore.Common/ThrottledBackgroundMessageProcessor.cs
- Mindscape.Raygun4Net.NetCore.Tests/ThrottledBackgroundMessageProcessorTests.cs
- Mindscape.Raygun4Net.NetCore/Storage/FileSystemCrashReportStore.cs
Should resolve #541 where up to 8 tasks workers can sit idle doing nothing when there's no messages to be sent. This change will create the task workers on demand based on the queue length and dispose of them if idle.
> Updated ThrottledBackgroundMessageProcessor to dynamically create task workers

- CHANGE-LOG.md
- Mindscape.Raygun4Net.Core/Diagnostics/PortableExecutableReaderExtensions.cs
- Mindscape.Raygun4Net.NetCore.Common/Diagnostics/PortableExecutableReaderExtensions.cs
This change is to prevent an exception from being thrown and then immediately caught within the `TryGetDebugInformation` method.
Its possible that in certain circumstances, a stack frame originates from a module that only exists in memory. In this situation, the name of the module will not be a locaiton on disk so loading that module from disk will fail. This causes the `PEReader` to be null.
> Prevent exception from being thrown and then immediately caught when getting debug information

- CHANGE-LOG.md
- Mindscape.Raygun4Net.Core/SimpleJson.cs
- Mindscape.Raygun4Net.NetCore.Common/SimpleJson.cs
- Mindscape.Raygun4Net.NetCore.Tests/SimpleJsonTests.cs
Fixes issue #307 where types that call `.ToString()` end up with `[Circular reference detected, object not serialized]` instead of the `ToString()` value.
> Fixed issue where Uri/Guid couldn't be serialized

- Mindscape.Raygun4Net.NetCore.Common/Builders/RaygunErrorMessageBuilder.cs
Addresses https://github.com/MindscapeHQ/raygun4net/issues/547
WinRT exceptions can have a value in the Exception.Data dictionary with a key of "__RestrictedErrorObjectReference" and a value of type WinRT.ObjectReferenceWithContext<WinRT.Interop.IUnknownVftbl>. When trying to serialize this value, a System.AccessViolationException is thrown which can crash the application, even if caught.
This PR is a candidate fix for this issue which take the approach of recognizing the Data dictionary key and not including the value in the report sent to Raygun.
> Filter out __RestrictedErrorObjectReference

- CHANGE-LOG.md
- Mindscape.Raygun4Net.Core/Messages/RaygunClientMessage.cs
When we has Assembly Info files in the old project files, this defaulted to `Raygun4Net` or similar, but the removal of the assembly info and move to new project files meant its set to `Mindscape.Raygun4Net` which unintentionally broke the grouping hasher for .NET Framework projects.
This removes looking up based on the Title and hard codes it to Raygun4Net so it doesn't break.
> Fix client name

- Mindscape.Raygun4Net.AspNetCore/ApplicationBuilderExtensions.cs
- Mindscape.Raygun4Net.NetCore/ApplicationBuilderExtensions.cs
- Raygun4Net.MSLogger.AspNetCore.Tests/Program.cs
Fixes #554 
Changed `GetService` to `GetRequiredService` for settings, and inadvertently changed the one for `IRaygunUserProvider` also.
Reproduced the issue by commenting out 
```
builder.Services.AddRaygunUserProvider();
```
Changed it to `GetService` app functions correctly again.
> Fixed user provider resolving

- Mindscape.Raygun4Net.NetCore.Common/Platforms/ApplePlatform.cs
As discussed on Slack, a customer has been facing issues where the method `MarshalManagedException` gets trimmed by the compiler, so crashes aren't captured.
The first approach I tried was to declare linker rules via xml configuration, but that only works if declared in the root project.
In order to offer a turn-key solution, I've found out that you can also declare the `DynamicDependency` directly in the class code. This will tell the compiler to not trim it. I have added it for both iOS and MacCatalyst platforms.
This has been tested using the provided sample code by the customer.
> fix: Add DynamicDependency declaration to preserve MarshalManagedException in iOS and MacOS apps

- Mindscape.Raygun4Net.NetCore.Common/Platforms/AndroidPlatform.cs
- Mindscape.Raygun4Net.NetCore.Common/Platforms/WindowsPlatform.cs
This PR adds the dynamic dependency definition for Android and Windows platform implementations. However, I am not sure how to effectively test this, I asked on Slack about which existing example project I can use for that, otherwise I will create new example projects.
> fix: add DynamicDependency definition for Windows and Android

- Mindscape.Raygun4Net.Core/RaygunSettings.cs
- Mindscape.Raygun4Net.NetCore.Tests/ThrottledBackgroundMessageProcessorTests.cs
- Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs
- Mindscape.Raygun4Net4.Tests/ThrottledBackgroundMessageProcessorTests.cs
- Mindscape.Raygun4Net4/RaygunClient.cs
- Mindscape.Raygun4Net4/ThrottledBackgroundMessageProcessor.cs
This PR ports the solution implemented in `Mindscape.Raygun4Net.NetCore.Common\ThrottledBackgroundMessageProcessor.cs` to `Mindscape.Raygun4Net4\ThrottledBackgroundMessageProcessor.cs`.
In order to support `Raygun4Net4`, it has been adapted to support the existing `Send` and `Enqueue` method. As well, a setting for the breakpoint at which new worker threads are added as been created.
The unit tests in `Mindscape.Raygun4Net4.Tests\ThrottledBackgroundMessageProcessorTests.cs` have been adapted, as well added the new test `Things_Throwing_Many` copied and adapted from the `NetCore` project.
The change passes CI checks in TeamCity, and has been tested using the project in https://github.com/MindscapeHQ/sample-apps/tree/master/src/FullFramework/Net462WebApplication
Fixes #558
> fix: #558 ported ThrottledBackgroundMessageProcessor from NetCore to Core

- Mindscape.Raygun4Net.Extensions.Logging/RaygunLogger.cs
Use null coalesce operator because scope data item value can be null.
When logging via `(ILogger)logger.Log..` in conjunction with `((ILogger)logger.BeginScope(new Dictionary<string,object?>() { "NullKey": null })` your logger throws a NullReferenceException.
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Mindscape.Raygun4Net.Extensions.Logging.RaygunLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\BuildAgent\work\97b7ce3b3781b48c\Mindscape.Raygun4Net.Extensions.Logging\RaygunLogger.cs:line 70
at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|14_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& …
```
> Update RaygunLogger.cs to use null coalesce operator because scope data item value can be null
