MindscapeHQ/raygun4net

Mindscape.Raygun4Net.Mvc.Tests/RaygunHttpModuleTests.cs, Mindscape.Raygun4Net.Mvc.sln, Mindscape.Raygun4Net.Mvc/RaygunExceptionFilterAttacher.cs, Mindscape.Raygun4Net/RaygunHttpModule.cs
https://github.com/MindscapeHQ/raygun4net/issues/241
=> Always add the RaygunExceptionFilterAttribute if there is a HandleErrorAttribute in the GlobalFilters list

Mindscape.Raygun4Net/SimpleJson.cs
.NET Native has an issue when attempting to cast an array into a class
with multiple generic types - e.g. a Dictionary<K,V>
=> .NET Native fix

Mindscape.Raygun4Net.WinRT/Builders/RaygunEnvironmentMessageBuilder.cs, Mindscape.Raygun4Net.WinRT/Messages/RaygunEnvironmentMessage.cs, Mindscape.Raygun4Net.WindowsStore/Builders/RaygunEnvironmentMessageBuilder.cs
windows-add-osversion
Gets the OS version - if it can - if it cant it will default to
string.Empty or what was used before.
Filip
=> Adding OS Version to message

AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Azure.WebJob.nuspec, Mindscape.Raygun4Net.Azure.WebJob.sln, Mindscape.Raygun4Net.Azure.WebJob/JobHostConfigurationExtensions.cs, Mindscape.Raygun4Net.Azure.WebJob/Mindscape.Raygun4Net.Azure.WebJob.csproj, Mindscape.Raygun4Net.Azure.WebJob/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.Azure.WebJob/RaygunExceptionHandler.cs, Mindscape.Raygun4Net.Azure.WebJob/RaygunProcessor.cs, Mindscape.Raygun4Net.Azure.WebJob/app.config, Mindscape.Raygun4Net.Azure.WebJob/packages.config, Mindscape.Raygun4Net.Azure.WebJob/readme.txt, build.ps1, package.ps1
Adds first class support for Azure WebJobs run using Azure Web Jobs SDK, which require custom exception handling compared to running a non Web Jobs SDK enabled console application for example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4net/324)
=> Raygun4net webjobs sdk

Mindscape.Raygun4Net.WebApi/Mindscape.Raygun4Net.WebApi.csproj, Mindscape.Raygun4Net.WebApi/RaygunWebApiDelegatingHandler.cs
Instead of reading entire contents and then trimming to 4096
This resolves #313 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4net/329)
=> Only read at most 4096 bytes of request content

Mindscape.Raygun4Net.AspNetCore/Builders/RaygunAspNetCoreRequestMessageBuilder.cs, Mindscape.Raygun4Net.AspNetCore/RaygunAspNetMiddleware.cs, Mindscape.Raygun4Net.AspNetCore/RaygunSettings.cs, Mindscape.Raygun4Net.AspNetCore/project.json, Mindscape.Raygun4Net.AspNetCore/project.lock.json, Mindscape.Raygun4Net.AspNetCore/readme.txt
Resolves #311, based on #317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4net/330)
=> Fix reading request data in aspnet core

Mindscape.Raygun4Net.AspNetCore/Builders/RaygunAspNetCoreRequestMessageBuilder.cs
StreamReader is left open - can't close or dispose as it closes the
Stream too which we don't want here, so replaced with alternative way of
reading the stream.
=> Replaced StreamReader with Stream.Read

Mindscape.Raygun4Net.WebApi/Extensions/RaygunHttpContentExtensions.cs, Mindscape.Raygun4Net.WebApi/Mindscape.Raygun4Net.WebApi.csproj, Mindscape.Raygun4Net.WebApi/RaygunWebApiFilters.cs, Mindscape.Raygun4Net.WebApi/RaygunWebApiMessageBuilder.cs, Mindscape.Raygun4Net/Messages/RaygunResponseMessage.cs, Mindscape.Raygun4Net/RaygunSettings.cs
This PR addresses issue https://github.com/MindscapeHQ/raygun4net/issues/334
=> Include http response exception message

Mindscape.Raygun4Net.Xamarin.Android/RaygunClient.cs, Mindscape.Raygun4Net.Xamarin.iOS/Batching/PulseEventBatch.cs, Mindscape.Raygun4Net.Xamarin.iOS/RaygunClient.cs
Thread safety around manually sending pulse messages via the Xamarin Raygun provider.
=> Xamarin pulse batch message thread safety

Mindscape.Raygun4Net.WebApi/RaygunWebApiFilters.cs, Mindscape.Raygun4Net.WebApi/RaygunWebApiMessageBuilder.cs
If it's not going to be sent, there's no reason to read it at all.
=> Don't read ignored response content.

Mindscape.Raygun4Net/Breadcrumbs/HttpBreadcrumbStorage.cs
Fixes #345
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mindscapehq/raygun4net/348)
=> Return empty list if HttpContext.Current is null

AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Xamarin.Android/Pulse.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunClient.cs, Mindscape.Raygun4Net.Xamarin.iOS/Batching/PulseEventBatch.cs, Mindscape.Raygun4Net.Xamarin.iOS/Pulse.cs, Mindscape.Raygun4Net.Xamarin.iOS/RaygunClient.cs, Mindscape.Raygun4Net.nuspec
Bug: RUM session was not ended when a new user was set resulting the new user details not being used in subsequent messages.
=> End RUM session when new user detected

AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Xamarin.iOS/RaygunClient.cs, Mindscape.Raygun4Net.nuspec
Do not wait for a response when sending Pulse messages.
=> Make all Pulse messages that are sent asynchronous.

Mindscape.Raygun4Net.Xamarin.Android/IRaygunMessageBuilder.cs, Mindscape.Raygun4Net.Xamarin.Android/Mindscape.Raygun4Net.Xamarin.Android.csproj, Mindscape.Raygun4Net.Xamarin.Android/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Xamarin.Android/packages.config, buildXamarinAndroid.sh
Building a separate NuGet package for this provider so it can be updated and used without referencing the main Raygun4Net package.
=> [XRAY-2377] Release Xamarin Android with its own NuGet package.

Mindscape.Raygun4Net.Core/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.WebApi.Signed.nuspec, Mindscape.Raygun4Net.WebApi.Tests/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.WebApi.nuspec, Mindscape.Raygun4Net.WebApi/Mindscape.Raygun4Net.WebApi.csproj, Mindscape.Raygun4Net.WebApi/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.WebApi/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.WebApi/RaygunWebApiDelegatingHandler.cs, buildWebApi.bat, buildWebApi.ps1, packageWebApi.bat, packageWebApi.ps1
Added null reference guard when checking request contents.
=> [XRAY-2393] Fix batch API requests causing null reference exception

Mindscape.Raygun4Net.Xamarin.Android.Tests/Mindscape.Raygun4Net.Xamarin.Android.Tests.csproj, Mindscape.Raygun4Net.Xamarin.Android/Messages/RaygunClientMessage.cs, Mindscape.Raygun4Net.Xamarin.Android/Mindscape.Raygun4Net.Xamarin.Android.csproj, Mindscape.Raygun4Net.Xamarin.Android/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.Xamarin.Android/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunClient.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunFile.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunFileManager.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunLogger.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunMessageBuilder.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunResponseStatusCode.cs
- Improve offline storage
- Update Android Mono version
=> [XRAY-2492] Update Xamarin Android

Mindscape.Raygun4Net.Xamarin.Android/Mindscape.Raygun4Net.Xamarin.Android.csproj, Mindscape.Raygun4Net.Xamarin.Android/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunClient.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunFileManager.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunSettings.cs
- Handle faulted tasks when sending stored reports
- Add option to allow customers to automatically flag unobserved task exceptions as observed when caught by the provider.
=> Xamarin Android - Add additional task exception handling

Mindscape.Raygun4Net.Xamarin.iOS.Unified/Mindscape.Raygun4Net.Xamarin.iOS.Unified.csproj, Mindscape.Raygun4Net.Xamarin.iOS.Unified/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Xamarin.iOS.Unified/RaygunFile.cs, Mindscape.Raygun4Net.Xamarin.iOS.Unified/RaygunFileManager.cs, Mindscape.Raygun4Net.Xamarin.iOS.Unified/RaygunLogLevel.cs, Mindscape.Raygun4Net.Xamarin.iOS.Unified/RaygunLogger.cs, Mindscape.Raygun4Net.Xamarin.iOS.Unified/RaygunResponseSatusCode.cs, Mindscape.Raygun4Net.Xamarin.iOS/RaygunClient.cs, Mindscape.Raygun4Net.Xamarin.iOS/RaygunSettings.cs
This PR looks to address task exception that occur when sending stored reports.
- Port offline support logic from Xamarin Android
- Include unobserved task exception handling logic
=> [XRAY-2615] Xamarin iOS Better Offline Storage Support

Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs
=> Remove null reference in CanSend method in RaygunClient. Fixes #412

.nuget/packages.config, AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Core.Signed.nuspec, Mindscape.Raygun4Net.Core.nuspec, Mindscape.Raygun4Net.Mvc.Signed.nuspec, Mindscape.Raygun4Net.Mvc.nuspec, Mindscape.Raygun4Net.Signed.nuspec, Mindscape.Raygun4Net.WebApi.Signed.nuspec, Mindscape.Raygun4Net.WebApi.nuspec, Mindscape.Raygun4Net.WebApi.sln, Mindscape.Raygun4Net.WebApi/Mindscape.Raygun4Net.WebApi.csproj, Mindscape.Raygun4Net.WebApi/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.WebApi/RaygunWebApiClient.cs, Mindscape.Raygun4Net.WebApi/RaygunWebApiDelegatingHandler.cs, Mindscape.Raygun4Net.WebApi/WebClientHelper.cs, Mindscape.Raygun4Net.nuspec, Mindscape.Raygun4Net/Mindscape.Raygun4Net.csproj, Mindscape.Raygun4Net/SimpleJson.cs, Mindscape.Raygun4Net4/Mindscape.Raygun4Net4.csproj, Mindscape.Raygun4Net4/RaygunClient.cs, Mindscape.Raygun4Net4/WebClientHelper.cs, build.bat, build.ps1, buildSigned.bat, buildSigned.ps1
Added shared singleton for instantiating the web client. cancelation token handler for canceled requests.
=> Added shared singleton for instantiating the web client.

Mindscape.Raygun4Net.NetCore.Common/Mindscape.Raygun4Net.NetCore.Common.csproj, Mindscape.Raygun4Net.NetCore.Tests/Mindscape.Raygun4Net.NetCore.Tests.csproj, Mindscape.Raygun4Net.NetCore.sln, Mindscape.Raygun4Net.NetCore/Mindscape.Raygun4Net.NetCore.csproj, Mindscape.Raygun4Net.NetCore/Properties/AssemblyInfo.cs, buildNetCore.ps1
Updated the .NETCore solution and projects to build with a sign configuration. 
Updated the buildNetCore script to build a sign version as well.
=> [XRAY-3800] A strong named version of the .NET Core provider

Mindscape.Raygun4Net.Xamarin.iOS.Unified/Mindscape.Raygun4Net.Xamarin.iOS.Unified.csproj, Mindscape.Raygun4Net.Xamarin.iOS.Unified/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.Xamarin.iOS.Unified/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Xamarin.iOS.Unified/RaygunLogger.cs
=> [XRAY-2615] Fix for Xamarin.iOS logging crashing applications.

Mindscape.Raygun4Net.Xamarin.Android.Tests/Mindscape.Raygun4Net.Xamarin.Android.Tests.csproj, Mindscape.Raygun4Net.Xamarin.Android.Tests/Properties/AndroidManifest.xml, Mindscape.Raygun4Net.Xamarin.Android/Mindscape.Raygun4Net.Xamarin.Android.csproj, Mindscape.Raygun4Net.Xamarin.Android/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.Xamarin.Android/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Xamarin.Android/RaygunClient.cs
=> [SUP] Null reference when completing async task

Mindscape.Raygun4Net.AspNetCore/Mindscape.Raygun4Net.AspNetCore.csproj, Mindscape.Raygun4Net.AspNetCore/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.AspNetCore/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.NetCore.Common/Mindscape.Raygun4Net.NetCore.Common.csproj, Mindscape.Raygun4Net.NetCore.Tests/Model/FakeRaygunClient.cs, Mindscape.Raygun4Net.NetCore/Mindscape.Raygun4Net.NetCore.csproj, Mindscape.Raygun4Net.NetCore/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.NetCore/Properties/AssemblyVersionInfo.cs
Merged: https://github.com/MindscapeHQ/raygun4net/pull/429
- Ensuring .NET Core projects build
- Updating version numbers
- Releasing to NuGet
=> [CR-203] Cleanup and release for .NET Core providers after PR merge

Mindscape.Raygun4Net.Xamarin.Android/Mindscape.Raygun4Net.Xamarin.Android.csproj, Mindscape.Raygun4Net.Xamarin.Android/RaygunClientBase.cs, Mindscape.Raygun4Net.Xamarin.Mac.Unified/Mindscape.Raygun4Net.Xamarin.Mac.Unified.csproj, Mindscape.Raygun4Net.Xamarin.Mac.Unified/RaygunClientBase.cs, Mindscape.Raygun4Net.Xamarin.Mac/Mindscape.Raygun4Net.Xamarin.Mac.csproj, Mindscape.Raygun4Net.Xamarin.Mac/RaygunClientBase.cs, Mindscape.Raygun4Net.Xamarin.iOS.Tests/Mindscape.Raygun4Net.Xamarin.iOS.Tests.csproj, Mindscape.Raygun4Net.Xamarin.iOS.Tests/Model/FakeRaygunClient.cs, Mindscape.Raygun4Net.Xamarin.iOS.Tests/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.Xamarin.iOS.Tests/RaygunClientTests.cs, Mindscape.Raygun4Net.Xamarin.iOS.Unified/Mindscape.Raygun4Net.Xamarin.iOS.Unified.csproj, Mindscape.Raygun4Net.Xamarin.iOS.Unified/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.Xamarin.iOS.Unified/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Xamarin.iOS/RaygunClientBase.cs
https://raygun.atlassian.net/browse/CR-259
Changes:
- Fixed the compilation issues for all Xamarin platforms
- Gave platforms their own copy of the RaygunClientBase class
- Updated Xamarin iOS provider version to 6.1.0
=> [CR-259] Release the Xamarin iOS changes to the storage directory

Mindscape.Raygun4Net.AspNetCore.sln, Mindscape.Raygun4Net.AspNetCore/Mindscape.Raygun4Net.AspNetCore.csproj, Mindscape.Raygun4Net.AspNetCore/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.AspNetCore2.Tests.TestLib/Mindscape.Raygun4Net.AspNetCore2.Tests.TestLib.csproj, Mindscape.Raygun4Net.AspNetCore2.Tests/Mindscape.Raygun4Net.AspNetCore2.Tests.csproj, buildNetCore.ps1
- Add signed AspNetCore task to the buildNetCore script
- Add Signed build configuration for the Raygun4Net.AspNetCore project
- Bump package version and assembly version
=> Release ASP.NET Core project

Mindscape.Raygun4Net.WebApi/README.md
Changes: 
- update code blocks
- some whitespace formatting
- format list
=> Fix the formatting of the WebAPI readme

AssemblyVersionInfo.cs, Mindscape.Raygun4Net.AspNetCore/Mindscape.Raygun4Net.AspNetCore.csproj, Mindscape.Raygun4Net.AspNetCore/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.AspNetCore/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.Core.Signed.nuspec, Mindscape.Raygun4Net.Core.nuspec, Mindscape.Raygun4Net.Core/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.Mvc.Signed.nuspec, Mindscape.Raygun4Net.Mvc.nuspec, Mindscape.Raygun4Net.Mvc/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.Mvc/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net.WebApi.Signed.nuspec, Mindscape.Raygun4Net.WebApi.nuspec, Mindscape.Raygun4Net.WebApi/Properties/AssemblyInfo.cs, Mindscape.Raygun4Net.WebApi/Properties/AssemblyVersionInfo.cs, Mindscape.Raygun4Net/Filters/RaygunKeyValuePairDataFilter.cs, Mindscape.Raygun4Net4/Properties/AssemblyInfo.cs
Changes:
- fix an exception when accessing string array out of bounds
=> Fix to the key value pair data filter

Mindscape.Raygun4Net.AspNetCore/Mindscape.Raygun4Net.AspNetCore.csproj
Fixes issue https://github.com/MindscapeHQ/raygun4net/issues/453
I'm not sure if there is some nuspec where .net5 is also needed
=> Added .net5 compilation target to AspNet core project

Mindscape.Raygun4Net.Mvc/README.md, Mindscape.Raygun4Net.WebApi/README.md, README.md
This PR is to update the ASP.NET WebAPI and MVC README documentation so that they are clear about being relevant for ASP.NET Framework, and where to go for ASP.NET Core docs
=> [ACT-64] Update ASP.NET Framework MVC and WebAPI READMEs

Mindscape.Raygun4Net.Mvc/README.md, Mindscape.Raygun4Net.WebApi/README.md
This PR is to update the ASP.NET MVC README documentation so that it is up to date and formatted correctly
=> [ACT-65] Update ASP.NET Framework MVC README documentation

CHANGE-LOG.md, GlobalAssemblyInfo.cs, Mindscape.Raygun4Net.AspNetCore/Mindscape.Raygun4Net.AspNetCore.csproj, Mindscape.Raygun4Net.NetCore.Common/Builders/EnvironmentProviders/DiskProvider.cs, Mindscape.Raygun4Net.NetCore.Common/Builders/EnvironmentProviders/MemoryProvider.cs, Mindscape.Raygun4Net.NetCore.Common/Builders/EnvironmentProviders/OSProvider.cs, Mindscape.Raygun4Net.NetCore.Common/Builders/EnvironmentProviders/ProcessorInfo.cs, Mindscape.Raygun4Net.NetCore.Common/Builders/EnvironmentProviders/ScreenProvider.cs, Mindscape.Raygun4Net.NetCore.Common/Builders/RaygunEnvironmentMessageBuilder.cs, Mindscape.Raygun4Net.NetCore.Common/Mindscape.Raygun4Net.NetCore.Common.csproj, Mindscape.Raygun4Net.NetCore.Tests/RaygunMessageBuilderTests.cs, Mindscape.Raygun4Net.NetCore/Mindscape.Raygun4Net.NetCore.csproj, pack-all.ps1
- Fixed Environment Information Memory
- Added cache for Environment Information to reduce overhead
- Added support for Environment Information on Windows/Linux/MacOS
- Changed CPU / OS information to be more accurate / understandable
=> Updated environment information

CHANGE-LOG.md
Missed the change log for v8.0.0
=> Add missing change-log for v8.0.0

CHANGE-LOG.md, Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs, Mindscape.Raygun4Net.NetCore/RaygunClient.cs, Raygun.CrashReporting.sln.DotSettings
Default timeout for the HttpClient is 100 seconds, this has been reduced to 30 seconds and the constructor updated to allow a custom HttpClient to be passed in.
=> Changes to HttpClient Timeout 

Mindscape.Raygun4Net.NetCore/README.md, README.md
=> Add CatchUnhandledExceptions to the installation instructions

CHANGE-LOG.md
=> Added change log for v9.0.3

CHANGE-LOG.md, Mindscape.Raygun4Net.AspNetCore/ApplicationBuilderExtensions.cs, Mindscape.Raygun4Net.AspNetCore/Builders/RaygunAspNetCoreRequestMessageBuilder.cs, Mindscape.Raygun4Net.AspNetCore/RaygunClient.cs, Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs, Mindscape.Raygun4Net.NetCore/RaygunClient.cs
Fixed up the constructors based on feedback from https://github.com/MindscapeHQ/NLog.Raygun/pull/16#issuecomment-2007791665
=> Fixed up the constructors and some minor cleanup

Mindscape.Raygun4Net.AspNetCore/README.md
Updated the readme to include changes from recent major versions 10 & 11.
=> Updated the Raygun4net.AspNetCore readme

.editorconfig, Mindscape.Raygun4Net.AspNetCore/Mindscape.Raygun4Net.AspNetCore.csproj, Mindscape.Raygun4Net.Azure.WebJob/Mindscape.Raygun4Net.Azure.WebJob.csproj, Mindscape.Raygun4Net.Azure.WebJob/RaygunExceptionHandler.cs, Mindscape.Raygun4Net.Core/Mindscape.Raygun4Net.Core.csproj, Mindscape.Raygun4Net.Mvc/Mindscape.Raygun4Net.Mvc.csproj, Mindscape.Raygun4Net.NetCore.Common/Mindscape.Raygun4Net.NetCore.Common.csproj, Mindscape.Raygun4Net.NetCore.Tests/Mindscape.Raygun4Net.NetCore.Tests.csproj, Mindscape.Raygun4Net.NetCore/Mindscape.Raygun4Net.NetCore.csproj, Mindscape.Raygun4Net.WebApi/Mindscape.Raygun4Net.WebApi.csproj, Mindscape.Raygun4Net4.Intergration.Tests/Mindscape.Raygun4Net4.Integration.Tests.csproj, Mindscape.Raygun4Net4/Mindscape.Raygun4Net4.csproj, global.json
Make sure the builds run in TeamCity/Linux, and enforces braces.
=> [Cleanup] Narrow target frameworks for tests and ensure we have braces

CHANGE-LOG.md
Update changelog with v11.2.3 changes
=> chore: prepare release v11.2.3

CHANGE-LOG.md, Mindscape.Raygun4Net.NetCore.Common/RaygunClientBase.cs, Mindscape.Raygun4Net.NetCore.Common/ThrottledBackgroundMessageProcessor.cs, Mindscape.Raygun4Net.NetCore.Tests/ThrottledBackgroundMessageProcessorTests.cs, Raygun.CrashReporting.sln
=> MaxWorkers in throttled background message processor is not respected
